### PR TITLE
Fix moving up and down in REPL

### LINKED ISSUE #349: Fail to press `UP` or `DOWN` keys in REPL after `v1.11.0-rc1`
Moving up and down failed when pressing the `UP` or `DOWN` key in the REPL after importing OhMyREPL, since `v1.11.0-rc1` or `v1.12.0-DEV`.

## Reproduction
1. Run `julia` with version `v1.11.0-rc1`.
2. Use the command `using OhMyREPL`.
3. Press the `UP` key (`\e[A`) or `DOWN` key (`\e[B`).

```log
$ julia +1.11
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-rc1 (2024-06-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using OhMyREPL

>>>>>> PRESS UP KEY <<<<<<

julia> ┌ Error: Error in the keymap
│   exception =
│    MethodError: no method matching enter_prefix_search(::REPL.LineEdit.MIState, ::REPL.LineEdit.HistoryPrompt, ::Bool)
│    The function `enter_prefix_search` exists, but no method is defined for this combination of argument types.
│
│    Closest candidates are:
│      enter_prefix_search(::REPL.LineEdit.MIState, ::REPL.LineEdit.PrefixHistoryPrompt, ::Bool)
│       @ REPL ~/.julia/juliaup/julia-1.11.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2203
│
│    Stacktrace:
│     [1] (::OhMyREPL.Prompt.var"#55#57"{REPL.LineEdit.HistoryPrompt})(::Any, ::Any, ::Vararg{Any})
│       @ OhMyREPL.Prompt ~/.julia/packages/OhMyREPL/6UG7a/src/repl.jl:291
│     [2] #invokelatest#2
│       @ ./essentials.jl:1043 [inlined]
│     [3] invokelatest
│       @ ./essentials.jl:1040 [inlined]
│     [4] (::REPL.LineEdit.var"#30#31"{OhMyREPL.Prompt.var"#55#57"{REPL.LineEdit.HistoryPrompt}, String})(s::Any, p::Any)
│       @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:1705
│     [5] macro expansion
│       @ ~/.julia/juliaup/julia-1.11.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2855 [inlined]
│     [6] macro expansion
│       @ ./lock.jl:273 [inlined]
│     [7] (::REPL.LineEdit.var"#282#284"{REPL.Terminals.TTYTerminal, REPL.LineEdit.ModalInterface, REPL.LineEdit.MIState, ReentrantLock, REPL.LineEdit.Prompt})()
│       @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2845
└ @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2857
julia>
julia>
```

### PR DESCRIPTION
**Pull request by huangyxi**
Fix #349 corresponding to https://github.com/JuliaLang/julia/pull/54674

https://github.com/JuliaLang/julia/pull/54674/files#diff-730f90e0bf9ca018477a1d4a52e0d7398af2bb8cf9e401568fd86690eec81bb7L1453-R1488

### CODE REVIEW

**Review by Moelf — APPROVED** [review]

File: src/repl.jl [hunk 1]
```diff
@@ -283,10 +283,12 @@ end
 NEW_KEYBINDINGS = create_keybindings()
 
 function insert_keybindings(repl = Base.active_repl)
-    mirepl = isdefined(repl,:mi) ? repl.mi : repl
+    mirepl = isdefined(repl,:mistate) ? repl.mistate : repl
     main_mode = mirepl.interface.modes[1]
-    p = mirepl.interface.modes[5]
+    php_idx = VERSION >= v"1.11.0-rc1" ? 6 : 5
+    p = mirepl.interface.modes[php_idx]::LineEdit.PrefixHistoryPrompt
```
Comment (IanButterworth) [inline src/repl.jl:289]: This seems brittle. Better to find first?

File: src/repl.jl [hunk 2]
```diff
@@ -283,10 +283,13 @@ end
 NEW_KEYBINDINGS = create_keybindings()
 
 function insert_keybindings(repl = Base.active_repl)
-    mirepl = isdefined(repl,:mi) ? repl.mi : repl
-    main_mode = mirepl.interface.modes[1]
-    p = mirepl.interface.modes[5]
+    mirepl = isdefined(repl,:mistate) ? repl.mistate : repl
+    interface_modes = mirepl.interface.modes
+    main_mode = interface_modes[1]
+    php_idx = findfirst(isa.(interface_modes, LineEdit.PrefixHistoryPrompt))
```
Comment (IanButterworth) [inline src/repl.jl:289]:
```suggestion
    php_idx = findfirst(isa(LineEdit.PrefixHistoryPrompt), interface_modes)
```
Avoid allocating

File: src/repl.jl (hunk 1 above)
Comment (huangyxi) [reply src/repl.jl]: Thanks. I have improved the implementation by using `findfirst`. (https://github.com/KristofferC/OhMyREPL.jl/pull/350/commits/8b6dc6ffbd672039c8cc70724eb3b1c9a2cf0e09#)

File: src/repl.jl (hunk 2 above)
Comment (huangyxi) [reply src/repl.jl:289]: Currently, `isa` requires two arguments explicitly. Here is a workaround:

```julia
findfirst(Base.Fix2(isa, LineEdit.PrefixHistoryPrompt), interface_modes)
```

However, I'm uncertain about using `Base.Fix2` since it hasn't been exported.

Comment (IanButterworth) [reply src/repl.jl:289]: Good point. It's fine to use Fix2, it's public, just not exported https://docs.julialang.org/en/v1/base/base/#Base.Fix2

**Review by IanButterworth — APPROVED** [review]
Seems good to me. Assuming the main mode is first is probably ok

**Comment by daviehh** [comment]
Thanks for the quick fix! If you do not wish to hard code by assuming main mode is first entry, one can replace the `main_mode = interface_modes[1]` line w/ something like

```julia
get_prompt_str = m -> LineEdit.prompt_string(isdefined(m, :prompt) ? m.prompt : "")
mm_idx_ = findfirst(m -> get_prompt_str(m) == REPL.JULIA_PROMPT, interface_modes) # main mode index
mm_idx = isnothing(mm_idx_) ? 1 : mm_idx_
main_mode = interface_modes[mm_idx]
```
